#!/bin/sh
# shellcheck disable=SC2086
#
# shield-trigger
#
# Copyright (C) 2007-2024
# Walter de Jong <walter@heiho.net>
# Jonathan Niehof <jtniehof@gmail.com>
# Jeffrey Clark <h0tw1r3@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

null_route() {
    TASK="$1"
    INET=""
    GW="127.0.0.1"
    if [ "${2#*:}" != "$2" ] ; then
        INET="-f inet6"
        GW="::1"
    fi

    if [ -x /sbin/ip ] ; then
        if [ "$TASK" = "show" ] ; then
            if /sbin/ip $INET route "$TASK" "$2" | read -r _x ; then
                return
            fi
            TASK="add"
        fi
        /sbin/ip $INET route "$TASK" blackhole "$2" 2>/dev/null
    else
        [ -n "$INET" ] && INET="-A inet6"
        /sbin/route $INET "$TASK" -host "$2" gw "$GW" dev lo
    fi
}

### usually no editing is needed beyond this point ###

log() {
    logger -i -t shield-trigger -p authpriv.info "$*"
}

usage() {
    echo "shield-trigger"
    echo "usage: ${0##*/} [add|del|sync] <IP number>"
    echo
    echo "shield-trigger is normally called by the pam_shield PAM module"
    exit 1
}

PATH=/sbin:/usr/sbin:/bin:/usr/bin

[ -z "$2" ] && usage

case "$1" in
    add)
        log "blocking $2"
        CMD="add"
        ;;

    del)
        log "unblocking $2"
        CMD="del"
        ;;

    sync)
        log "sync $2"
        CMD="show"
        ;;

    *)
        usage
        ;;
esac

null_route "$CMD" "$2"

exit 0 # make pam_shield happy
